version: "3"
services:
  app-dev:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db-dev
  db-dev:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SSMS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SSMS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SSMS_DB}
    volumes:
      - ssms-db-data-dev:/var/lib/postgresql/data
  pgadmin-dev:
    container_name: ssms-pgadmin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${SSMS_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${SSMS_PGADMIN_PASSWORD}
    ports: 
      - "5050:80"
    depends_on:
      - db-dev
volumes:
  ssms-db-data-dev:
    driver: local