version: "3"
services:
  app:
    build: .
    command: bash -c "alembic upgrade head && python main.py"
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SSMS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SSMS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SSMS_DB}
    volumes:
      - ssms-db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: ssms-pgadmin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${SSMS_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${SSMS_PGADMIN_PASSWORD}
    ports: 
      - "5050:80"
    depends_on:
      - db
volumes:
  ssms-db-data:
    driver: local